name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        php: [ 7.4, 7.3 ]
        laravel: [ 7.*, 6.*, 5.8.* ]
        stability: [ prefer-stable ]
        include:
          - laravel: 7.*
            testbench: 5.*
            carbon: 2.*
          - laravel: 6.*
            testbench: 4.*
            carbon: 2.*
          - laravel: 5.8.*
            testbench: 3.*
            carbon: 2.*
    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: xdebug

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "nesbot/carbon:${{ matrix.carbon }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: List Installed Dependencies
        run: composer show -D

      - name: Execute tests and coverage
        run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

      - name: Upload coverage results to Coveralls
        uses: coverallsapp/github-action@v2
        env:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          # Note: This is the only path that the Coveralls GitHub Action supports.
          # So we cannot use something like .Build/coverage/clover.xml here.
          file: build/logs/clover.xml